# Generated by Django 4.2.1 on 2023-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("organization", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
