# Generated by Django 4.2.1 on 2023-08-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressBook", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="address",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="organization",
        ),
        migrations.AddField(
            model_name="contact",
            name="notes",
            field=models.TextField(null=True, unique=True),
        ),
    ]
