# Generated by Django 4.2.1 on 2023-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressBook", "0002_remove_contact_address_remove_contact_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
