# Generated by Django 4.2.1 on 2023-08-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressBook", "0003_alter_contact_name_alter_contact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
