# Generated by Django 4.2.1 on 2023-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addressBook", "0005_alter_contact_name_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
